/**
 * Created by urunzl on 4.10.2016.
 */

var selectionConstants = {
    SWITCH_GROUP: "SWITCH_GROUP",
    SWITCH_UNIT: "SWITCH_UNIT",
    SWITCH_SHIFT: "SWITCH_SHIFT",
    SWITCH_ARTICLE: "SWITCH_ARTICLE",
    SET_SHIFTS: "SET_SHIFTS",
    SET_GROUPS: "SET_GROUPS",
    SET_ACTIVE_ITEM: "SET_ACTIVE_ITEM",
    SET_ACTIVE_SHIFT: "SET_ACTIVE_SHIFT",
    SET_SHIFT_ACTIVE: "SET_SHIFT_ACTIVE"
};

module.exports = selectionConstants;