/**
 * Created by urunzl on 20.10.2016.
 */
var settingsConstants = {
    SET_PRODUCT_PACKAGE: "SET_PRODUCT_PACKAGE",
    SET_PRODUCT_SPEED: "SET_PRODUCT_SPEED",
    SET_PRODUCT_QSI: "SET_PRODUCT_QSI",
    SET_PRODUCT_FSI: "SET_PRODUCT_FSI",
    SET_PRODUCT_FSI_AFTERStop: "SET_PRODUCT_FSI_AFTERStop",
    SET_PRODUCT_FSI_AFTERCut: "SET_PRODUCT_FSI_AFTERCut",
    SET_PRODUCT_AMISpin: "SET_PRODUCT_AMISpin",
    SET_PRODUCT_ROTOR: "SET_PRODUCT_ROTOR",
    SET_PRODUCT_AIR: "SET_PRODUCT_AIR",
    SET_PRODUCT_SVL: "SET_PRODUCT_SVL",
    SET_QM_CHANNELS: "SET_QM_CHANNELS",
    SET_QM: "REFRESH_ITEM",
    SET_Q_ALARMS: "SET_Q_ALARMS",
    SET_Y_ALARMS: "SET_Y_ALARMS",
    SET_PIECER: "SET_PIECER",
    SET_SLCM_SETTING: "SET_SLCM_SETTING",
    SET_TECH_ALARMS: "SET_TECH_ALARMS"
};

module.exports = settingsConstants;