/**
 * Created by urunzl on 20.10.2016.
 */
var settingsConstants = {
    SET_PRODUCT_PACKAGE: "SET_PRODUCT_PACKAGE",
    SET_PRODUCT_SPEED: "SET_PRODUCT_SPEED",
    SET_PRODUCT_QSI: "SET_PRODUCT_QSI",
    SET_PRODUCT_FSI: "SET_PRODUCT_FSI",
    SET_PRODUCT_FSI_AFTERStop: "SET_PRODUCT_FSI_AFTERStop",
    SET_PRODUCT_FSI_AFTERCut: "SET_PRODUCT_FSI_AFTERCut",
    SET_PRODUCT_AMISpin: "SET_PRODUCT_AMISpin",
    SET_PRODUCT_ROTOR: "SET_PRODUCT_ROTOR",
    SET_PRODUCT_AIR: "SET_PRODUCT_AIR",
    SET_PRODUCT_SVL: "SET_PRODUCT_SVL"
};

module.exports = settingsConstants;